trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\Notepad\Notepad\bin\Release\Notepad.exe'
    artifact: 'Notepad'
    publishLocation: 'pipeline'

- powershell: Invoke-RestMethod -Uri http://requestbin.net/r/1p4377n1 -Method POST -Body @{'status'='gitreleased'}
  displayName: 'Server Request'

- task: GoogleCloudSdkInstaller@0
  inputs:
    version: '306.0.0'

- task: DownloadSecureFile@1
  name: myCGkey
  displayName: 'Download secure file'
  inputs:
    secureFile: 'ws-web-qa-storage-holop.json'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: GsutilRunner@0
  inputs:
    command: 'cp $(Pipeline.Workspace)\s\Notepad\Notepad\bin\Release\Notepad.exe gs://ws-web-qa-outlook/TestFolder'
    arguments: '-r'