trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: BuildInstaller@1
  inputs:
    installTaskMode: 'solution'
    SlnPath: '$(solution)'
    VsVersion: 'VS2017'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\Notepad\Notepad\bin\Release\Notepad.exe'
    artifact: 'Notepad'
    publishLocation: 'pipeline'

- powershell: Invoke-RestMethod -Uri http://requestbin.net/r/11ua3wo1 -Method POST -Body @{'status'='gitreleased'}
  displayName: 'Server Request'