trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: CmdLine@2
  inputs:
    script: 'DisableOutOfProcBuild.exe'
    workingDirectory: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'

- task: DevEnvBuild@2
  inputs:
    solution: '**/*.sln'
    buildCfg: 'Release'
    vsVersion: '16.0'
    project: 'Notepad/NotepadSetup/NotepadSetup.vdproj'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\Notepad'
    artifact: 'Notepad'
    publishLocation: 'pipeline'

- task: DownloadSecureFile@1
  name: myCer
  displayName: 'Download secure file'
  inputs:
    secureFile: 'vcita_systems_ltd.p12'

- task: GoogleCloudSdkInstaller@0
  inputs:
    version: '306.0.0'

- task: GcloudRunner@0
  inputs:
    command: 'auth activate-service-account storage-holop@ws-web-qa.iam.gserviceaccount.com --key-file=$(myCGkey.secureFilePath)'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.9'
    addToPath: true
    architecture: 'x64'

- task: CmdLine@2
  name: "Push_To_GCloud"
  env:
    CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
  inputs:
    script: |
      gsutil cp $(Pipeline.Workspace)\s\Notepad\Notepad\bin\Release\Notepad.exe gs://ws-web-qa-outlook/TestFolder