trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: GoogleCloudSdkInstaller@0
  inputs:
    version: '306.0.0'

- task: DownloadSecureFile@1
  name: myCGkey
  displayName: 'Download secure file'
  inputs:
    secureFile: 'ws-web-qa-storage-holop.json'

- task: GcloudRunner@0
  inputs:
    command: 'auth activate-service-account storage-holop@ws-web-qa.iam.gserviceaccount.com --key-file=$(myCGkey.secureFilePath)'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.9'
    addToPath: true
    architecture: 'x64'

- task: GsutilRunner@0
  inputs:
    command: 
    arguments: '--version'

- task: CmdLine@2
  name: "Push_To_GCloud"
  env:
    CLOUDSDK_PYTHON: $(env.pythonLocation)\python.exe
  inputs:
    script: |
      C:\hostedtoolcache\windows\google-cloud-sdk\306.0.0\x64\bin\gsutil.cmd --version