trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DevEnvBuild@2
  inputs:
    solution: '**\NotepadSetup\NotepadSetup.vdproj'
    buildCfg: 'Release'
    vsVersion: '16.0'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\Notepad'
    artifact: 'Notepad'
    publishLocation: 'pipeline'

- powershell: Invoke-RestMethod -Uri http://requestbin.net/r/11ua3wo1 -Method POST -Body @{'status'='gitreleased'}
  displayName: 'Server Request'